- xmpp.go
Much needed function for me and the bot we're developing using this awesome library, thought a pull request would be in order.
XHTML-IM protocol: http://www.xmpp.org/extensions/xep-0071.html
> Add ability to send message as html

- xmpp.go
Hello.
I'm using this library for my xmpp-service, but I get a trouble, app become consume 100% cpu when I have a problems with net.
After recompiling with debug tables, I'm attached to process with gdb. And when process become consume 100% cpu, I found the problem in one eternal cycle.
Trace:
```
(gdb) n
t, err := p.Token()
(gdb) n
if err != nil && err != io.EOF {
(gdb) n
switch t := t.(type) {
(gdb) n
t, err := p.Token()
(gdb) n
if err != nil && err != io.EOF {
(gdb) n
switch t := t.(type) {
(gdb) n
t, err := p.Token()
(gdb) n
if err != nil && err != io.EOF {
(gdb) n
switch t := t.(type) {
(gdb) n
t, err := p.Token()
(gdb) n
if err != nil && err != io.EOF {
(gdb) n
switch t := t.(type) {
(gdb) n
t, err := p.Token()
(gdb) n
if err != nil && err != io.EOF {
(gdb) n
switch t := t.(type) { …
```
> fix eternal cycle with malicious xml packet

- _example/example.go
- xmpp.go
Anonymous auth isn't attempted and an error is raised if the username and password are empty even if a server has anonymous auth as an option.  When a JID isn't specified and a password isn't as well, the only option left is anonymous auth.  Anonymous auth is also probably the intention in the case of no JID or password.  This bypasses the logic which validates a JID in that case and attempts only SASL with mechanism ANONYMOUS.  If JID or password are not empty or if ANONYMOUS is not a negotiable authentication mechanism, errors will still be raised.
> ANONYMOUS auth by default if user and password are empty.

- xmpp.go
Having the ability to check up on the delay timestamp provides further extensibility. We use it to make sure specific commands sent over xmpp chat was not a delayed command.
> Include delay in chats

- xmpp.go
XML Decoder is allocated in startStream so
it overwrites the one allocated in init()
> Remove extra allocation of XML Decoder

- xmpp_ping.go
Hey!
With this patch error codes are returned for the PingC2S and PingS2S methods. This is necessary to build highly available and fault tolerant services...
Cheers, Philip
> Ping: return errors

- xmpp.go
Hey!
As promised, here is another pull request regarding the C2S Ping! :D `Recv()` now can also handle the Pong response that is wrapped in a `<iq/>` tag, so I also created a new `type IQ`.
Greetings, Philip
> Recv: handle clientIQ

- xmpp.go
- xmpp_ping.go
Though a client function, client ping does not use the client jid.
Fixed ping to use the obtained jid and configured server domain by default.
Client now exposes jid, which can be handy in some cases.
> Xmpp ping fixed to use the obtained jid.

- xmpp.go
- xmpp_discovery.go
couple thing I noticed while investigating implementing discovery:
1) func (c *Client) init(o Options) is a beast of a function, tons of code 0 tests.
2) Client.domain is never set anywhere? (hence setting it in the init function) you can literally remove it and code still compiles.
> Implement discovery

- xmpp.go
This pull-request will add the "SendKeepAlive" method to be able to send a whitespace keepalive message to the server in order to check if the connection is still alive. See also https://tools.ietf.org/html/rfc6120#section-4.6.1
> Add SendKeepAlive method to send "whitespace keepalive"

- xmpp_muc.go
This fixes an XML error when joining a MUC with NoHistory as history_type.
My connected Client responded with "EOF" (when calling Client.Recv) after sending a presence to a MUC, I had to investigate on the server side to find the error.
> Fix MUC NoHistory invalid XML

- xmpp.go
- xmpp_test.go
This was probably catched in most cases after commit 9dd92e1, but was at best misleading as it suggested that the end of input stream signal from xml.Decoder was intentionally ignored.
Ref mattn/go-xmpp#28
> Fix neglected io.EOF handling

- xmpp.go
This allows to use a different writer than os.Stderr to write debugging
output to.
This is a small non-breaking change which allows to debug terminal application using go-xmpp.
> introduce DebugWriter

- xmpp.go
- xmpp_pubsub.go
This PR is supposed to be the first in order to solve #118 by first implementing the ability to subscribe to PubSub nodes and request their data.
What I am not sure about is my choice to replace the big if-then-else block with an empty switch  statement. In my further patch writing, it made the code more readable, but I can change it.
Also I am sure that I messed up somewhere as I had to rebase this multiple times and it seems as if my editor was not set to Golang.
> Implement XEP-0060

- xmpp.go
- xmpp_avatar.go
This PR allows go-xmpp to request a user's avatar data or metadata and also react to avatar notifications via PubSub.
This PR was tested with a modified example that basically just requests a subscription to the metadata node, requests the metadata and upon receiving it, request the avatar data. 
It should be noted (Perhaps I can write a comment somehwhere in another commit?) that notifications via PubSub can only be received if a presence subscription exists. Though it is stated in XEP-0060, it is - at least for me - non-obvious if you havent read the specification.
This PR closes #118
> Implement XEP-0084 (User Avatar)

- xmpp.go
tls.Config contains fields of type sync.Once and sync.RWMutex. My understanding
is that if the copy happens to occur while the lock is in a locked state, the
lock will remain locked indefinitely and cause a deadlock. Instead use
tls.Config.Clone() to create a shallow copy.
Also the lock copy made `go vet` upset:
$ go vet ./...
./xmpp.go:242:17: assignment copies lock value to newconfig: crypto/tls.Config contains sync.Once contains sync.Mutex
./xmpp.go:530:9: assignment copies lock value to *tc: crypto/tls.Config contains sync.Once contains sync.Mutex
> Avoid creating copies of locks

- xmpp.go
This makes other pubsub requests accessible via
client.Recv().
> Return all pubsub IQs.

- xmpp.go
- xmpp_test.go
**Problem:**
OtherElem list has xml elements that are not part of the basic xmpp stanza. While go-xmpp collects sub elements into innerXML string correctly, it loses xml attributes for the outermost xml element.
**Solution:**
Add attribute collection to XMLElement and let Go xml parsing do the work.
**Side effects:**
Should be minimal. XMLElement is used only in a few places and an added interface member does not affect any of the other actions it is used in.
**Benefits:**
Possible to work with the attributes of the containing Other Element. Anybody who adds their own tags (like IoT devices) will have an easier time if some of the attributes aren't lost.
**Changes:**
1. Added line to XMLElement definition to include attributes and give the xml parser info to parse the attributes
2. Added …
> Add xml attribute support for XMLElement

- xmpp.go
- xmpp_information_query.go
- xmpp_muc.go
- xmpp_ping.go
- xmpp_subscription.go
When debugging issues it would often be useful to also
see the messages that are sent.
I didn't find a way to do it as simple as you managed 
to do it for received stanzas but from the different
approaches I tried this seems to be the best one.
I purposely didn't enable printing stanzas sent during
auth to prevent people from accidentally pasting their
credentials when showing logs.
> Print sent stanzas in debug mode.

- xmpp.go
Add support for XEP-0474
The upcoming ejabberd release supports XEP-0474 [1] wich requires support for 
the `d=` parameter. Currently we fail if an unknown parameter is set and `d=`
is unknown.
Instead of just not failing when `d=` is set I added support for the downgrade
protection.
[1] https://xmpp.org/extensions/xep-0474.html
> Authentication improvements.

- xmpp.go
- SCRAM: Add support for tls-server-end-point channel binding.
- Simplify tls-server-end-point channel binding code.
- (Indirectly) check that TLS was not renegotioated when using "tls-server-end-point".
> Tls-server-end-point improvements.

- xmpp.go
According to RFC 5802 5.1 only the "m" attribute should
cause an authentication error.
> Improve RFC5802 compatibility.

- go.mod
- go.sum
- xmpp.go
- xmpp_information_query.go
I added some basic support for [XEP-0388: Extensible SASL Profile](https://xmpp.org/extensions/xep-0386.html) and [XEP-0386: Bind 2](https://xmpp.org/extensions/xep-0386.html).
@mattn as this would introduce a new dependency ([google/uuid](https://github.com/google/uuid) as XEP-0388 requires the use of a valid UUIDv4) I'd like to ask your opinion.
> Add support for SASL2 and BIND2

- xmpp_information_query.go
Just to make requests in conventional way.
In my case it is disco#info to MUC.
> Add DiscoverInfo() as thin wrapper around RawInformation()

- _example/example-gui.go
- _example/example.go
I'm compiling _example/example.go and get fail, tls.Config should be pointer
```bash
cd _example;
_example git:(master) go build -o example ./example.go 
./example.go:46:24: cannot use tls.Config{…} (value of struct type tls.Config) as *tls.Config value in assignment
```
> fix(example): tls.Config should be pointer
