xmpp.go

Showstopper when running go vet.

Remove unreacheable panics

---

xmpp.go
xmpp_ping.go
xmpp_subscription.go

Add OAuth2 support
Use provided host for certificate verification
Remove redundant ANONYMOUS mechanism support

Add OAuth2 support & Use provided host for certificate verification

---

xmpp.go

I just add the status into the Presence structure.

Add Status into Presence struct

---

README.md

So its obvious that this project has an documentation.

Update README.md - Add a link to the Documentation

---

xmpp.go

Fix client no StartTLS & server no required

---

xmpp.go
xmpp_information_query.go

Note variable no_proxy for hosts that should not connect via the proxy.
Add method to send an iq frame that not contains a query element.

Proxy handling / additional send method

---

xmpp.go

See https://xmpp.org/extensions/xep-0066.html#x-oob
Work from https://github.com/matterbridge/go-xmpp/pull/2

Add support for out of band data

---

xmpp.go

Add the ability to customize the connection timeout

---

xmpp.go

use ServerName to verify tls hostname

---

xmpp.go

I was actually making an attempt to use XMPP anonymous connection. And when trying to connect it seems to not sending a domain (host) to the XMPP server. So I fixed that.

Fix host with anonymous connection

---

xmpp.go

Provide error replies for IQs.

---

xmpp_subscription.go

https://www.rfc-editor.org/rfc/rfc6121.html#section-3.3.1

Unsubscribing

---

xmpp.go

- Remove unnecessary newline.
- Make success content available.

success msg

---

xmpp.go
xmpp_disco.go
xmpp_information_query.go

In order to learn what the server or a different user supports, I had to expand the support of XEP-0030 a bit.
**EDIT**: It seems that this PR breaks the PubSub functionality. I am working on a fix.

Implement Disco queries against other entities

---

xmpp.go

fix syntax errors

---

xmpp.go

- Fix syntax errors.
- gofmt
- Add SCRAM-SHA-1, SCRAM-SHA-256 and SCRAM-SHA-512 auth

add scram auth

---

xmpp.go
xmpp_information_query.go
xmpp_muc.go
xmpp_ping.go
xmpp_subscription.go

This got reworked to also work with multiple connections
as pointed out by @vcabbage in
https://github.com/mattn/go-xmpp/pull/141#issuecomment-1557334066

Rework printing of sent stanzas when debug is enabled

---

xmpp.go
xmpp_information_query.go
xmpp_muc.go
xmpp_ping.go
xmpp_subscription.go

Now there should be no more newlines in between any stanza and a
newline after every stanza.
This should not affect functionality but is looking better if
stanzas are printed for debugging.

Harmonize newlines

---

README.md
go.mod
xmpp.go

- Fix manual choice of auth mechanism.
- Change import path to xmppo/go-xmpp
- Fix doc url.

Change import path to xmppo/go-xmpp

---

xmpp.go

- Improve readability of switch statement for auth mechanism choice
- Improve error message when no viable authentication method was found.
- Fix manual choice of auth mechanism.
- Change import path to xmppo/go-xmpp
- Fix doc url.

Readability improvements.

---

xmpp.go

Make use of Presence.{Type,Show,Status} fields in SendPresence() to send actual client status to server and chat rooms.

Extend SendPresence() stub func to allow send useful statuses

---

xmpp.go

Filter invalid UTF8 from message body.

---

xmpp.go

Avoids a global mutex which could end up unexpectedly blocking a separate client. For example, if there were a client with few messages and a client with many messages, the client with few could hold the lock waiting for a token blocking the client with many from receiving.

move nextMutex to Client to prevent blocking separate Clients
